### ISSUE TITLE
Only short labels for pop-up menus for a narrower window

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#93]
As proposed in a private branch before, I'd like to forward this once more for consideration.
Instead of showing the full description of format/codecs, like "_AVI (Audio Video Interleaved)_", only show the extension/abbreviation of the chosen option. Only show the long version when invoking the popup menu:

Now - wide:
<img src="https://user-images.githubusercontent.com/6107158/218142000-dcbd44aa-c112-48df-aa94-c34216c4dd55.png" width="432px" />

Proposal - narrow:
<img src="https://user-images.githubusercontent.com/6107158/218139085-b6020c6d-2982-4469-b87c-2d337f7789e5.png" width="335px" />

As you can see, the propsal results in a much narrower window.
* minimum width at 12pt fonts: 671px vs. 865px (won't fit an old school 800x600 screen)
* no exceedingly wide spinner text fields (e.g. Audio channels) and pop-up menus (e.g. Audio codec)
* more space for the output file path, because the format extensions are  only 3 or 4 characters long

**Comment by andimachovec** [comment]
I´m not that happy with the long labels either, mostly because in some cases it´s hard to recognize which format or codec is actually meant. Especially the formats are mostly remembered by the file extensions or short forms. 
The questions is if we use the code that changes the labels on activating the popup, or just go ahead and shorten the labels completely. I tend to think the latter is the better solution. Mainly because the concept of popup menus changing labels while opening and closing them is a pretty unfamiliar concept, at least to me. I can´t remember using any application (on any OS) that does that.

**Comment by humdingerb** [comment]
As long as the "long labels" start the same as the shortened ones, I don't think the user gets confused.
E.g.: "wmv1" - "wmv1 - Windows Media Video 7"

In this case, it may even provide vital information compared to either just using "wmv1" or "Windows Media Video 7". Because some people may know "wmv1" but not that that's "Windows Media Video 7", and vice-versa.

Anyhow, since I already migrated my previous changes to current master before reading your comment, I just create a PR for it and let you play around with it some more. :)

**Comment by andimachovec** [comment]
I like it. Not confusing at all. Let's merge it.
