### ISSUE TITLE
[SUGGESTION] Smarter interface

### ISSUE THREAD

**Issue by forart** [HaikuArchives/ffmpegGUI#99]
Since our [Haiku port](https://github.com/cdgriffith/FastFlix/issues/173) request seems to be failed, it would be interesting to "grab some inspiration" from @cdgriffith's [FastFlix](https://github.com/cdgriffith/FastFlix/) GUI that looks quite smart (and is tab-arranged too):

![](https://raw.githubusercontent.com/cdgriffith/FastFlix/master/docs/gui_preview.png)

Hope that inspires.

**Comment by humdingerb** [comment]
Try "overwhelming" instead of "smarter"...
I don't think ffmpegGUI should try to present every possible option of ffmpeg, let alone in a single crowded window. It also won't become a big video editing suite. It's a simple tool and should stay this way.

Also, simply pointing to some other app is too unspecific for an issue IMO. But that's par for the course, of course...

**Comment by forart** [comment]
Of course it's not an "issue", but just a "suggestion" (as specified in the title)...

...anyway we do to agree: not **any** possible option of ffmpeg is needed, anyway more would be useful (nowdays).

Thanks anyway for your attention.

**Comment by andimachovec** [comment]
I know this issue is already closed but I still wanted to add my 2 cents here: 
In no way do I want to put down the efforts of the Fastflix developers, but I think the screenshot of the interface can serve as a good example what we don't want with ffmpegGUI. @humdinger already outlined it in his answer. To me the interface of Fastflix is almost as overwhelming as the commandline options list of ffmpeg itself. We want to simplify that and give the non-technical or less commandline-savvy user access to the more common options and use cases of ffmpeg. And by showing the generated commandline (in an editable way) we also provide the ability to add custom options that are not available through the GUI. 

@forart: What would be quite valuable to us would be if you could give us a list of maybe 5 or 6 advanced ffmpeg options that are important to you and that ffmpegGUI currently doesn't have. We could add them to our currently hidden advanced options tab.

**Comment by forart** [comment]
@andimachovec As already claimed in the [other "issue"](https://github.com/HaikuArchives/ffmpegGUI/issues/98) and [reiterated on the haiku forum](https://discuss.haiku-os.org/t/help-how-to-delete-our-account/13134), we're not interested anymore in Haiku nor in any related project.

Thanks anyway.
